/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContratarRouteImport } from './routes/contratar'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProfissionalRouteImport } from './routes/profissional'
import { Route as SejaProfissionalRouteImport } from './routes/seja-profissional'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin.avaliacoes'
import { Route as AdminCancelamentosRouteImport } from './routes/admin.cancelamentos'
import { Route as AdminCarrosselRouteImport } from './routes/admin.carrossel'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminContratacoesRouteImport } from './routes/admin.contratacoes'
import { Route as AdminExtrasRouteImport } from './routes/admin.extras'
import { Route as AdminListaEsperaRouteImport } from './routes/admin.lista-espera'
import { Route as AdminOrquestraRouteImport } from './routes/admin.orquestra'
import { Route as AdminPrecosRouteImport } from './routes/admin.precos'
import { Route as AdminProfissionaisRouteImport } from './routes/admin.profissionais'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as ConfirmacaoIdRouteImport } from './routes/confirmacao.$id'
import { Route as OportunidadeTokenRouteImport } from './routes/oportunidade.$token'
import { Route as ProfissionalEntrarRouteImport } from './routes/profissional_.entrar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratarRoute = ContratarRouteImport.update({
  id: '/contratar',
  path: '/contratar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalRoute = ProfissionalRouteImport.update({
  id: '/profissional',
  path: '/profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaProfissionalRoute = SejaProfissionalRouteImport.update({
  id: '/seja-profissional',
  path: '/seja-profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCancelamentosRoute = AdminCancelamentosRouteImport.update({
  id: '/cancelamentos',
  path: '/cancelamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarrosselRoute = AdminCarrosselRouteImport.update({
  id: '/carrossel',
  path: '/carrossel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContratacoesRoute = AdminContratacoesRouteImport.update({
  id: '/contratacoes',
  path: '/contratacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExtrasRoute = AdminExtrasRouteImport.update({
  id: '/extras',
  path: '/extras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListaEsperaRoute = AdminListaEsperaRouteImport.update({
  id: '/lista-espera',
  path: '/lista-espera',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrquestraRoute = AdminOrquestraRouteImport.update({
  id: '/orquestra',
  path: '/orquestra',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrecosRoute = AdminPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfissionaisRoute = AdminProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacaoIdRoute = ConfirmacaoIdRouteImport.update({
  id: '/confirmacao/$id',
  path: '/confirmacao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadeTokenRoute = OportunidadeTokenRouteImport.update({
  id: '/oportunidade/$token',
  path: '/oportunidade/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalEntrarRoute = ProfissionalEntrarRouteImport.update({
  id: '/profissional_/entrar',
  path: '/profissional/entrar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/contratar': typeof ContratarRoute
  '/entrar': typeof EntrarRoute
  '/minha-conta': typeof MinhaContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profissional': typeof ProfissionalRoute
  '/seja-profissional': typeof SejaProfissionalRoute
  '/termos': typeof TermosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cancelamentos': typeof AdminCancelamentosRoute
  '/admin/carrossel': typeof AdminCarrosselRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/contratacoes': typeof AdminContratacoesRoute
  '/admin/extras': typeof AdminExtrasRoute
  '/admin/lista-espera': typeof AdminListaEsperaRoute
  '/admin/orquestra': typeof AdminOrquestraRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/profissionais': typeof AdminProfissionaisRoute
  '/admin/login': typeof AdminLoginRoute
  '/confirmacao/$id': typeof ConfirmacaoIdRoute
  '/oportunidade/$token': typeof OportunidadeTokenRoute
  '/profissional/entrar': typeof ProfissionalEntrarRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/contratar': typeof ContratarRoute
  '/entrar': typeof EntrarRoute
  '/minha-conta': typeof MinhaContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profissional': typeof ProfissionalRoute
  '/seja-profissional': typeof SejaProfissionalRoute
  '/termos': typeof TermosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cancelamentos': typeof AdminCancelamentosRoute
  '/admin/carrossel': typeof AdminCarrosselRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/contratacoes': typeof AdminContratacoesRoute
  '/admin/extras': typeof AdminExtrasRoute
  '/admin/lista-espera': typeof AdminListaEsperaRoute
  '/admin/orquestra': typeof AdminOrquestraRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/profissionais': typeof AdminProfissionaisRoute
  '/admin/login': typeof AdminLoginRoute
  '/confirmacao/$id': typeof ConfirmacaoIdRoute
  '/oportunidade/$token': typeof OportunidadeTokenRoute
  '/profissional/entrar': typeof ProfissionalEntrarRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/contratar': typeof ContratarRoute
  '/entrar': typeof EntrarRoute
  '/minha-conta': typeof MinhaContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profissional': typeof ProfissionalRoute
  '/seja-profissional': typeof SejaProfissionalRoute
  '/termos': typeof TermosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cancelamentos': typeof AdminCancelamentosRoute
  '/admin/carrossel': typeof AdminCarrosselRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/contratacoes': typeof AdminContratacoesRoute
  '/admin/extras': typeof AdminExtrasRoute
  '/admin/lista-espera': typeof AdminListaEsperaRoute
  '/admin/orquestra': typeof AdminOrquestraRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/profissionais': typeof AdminProfissionaisRoute
  '/admin_/login': typeof AdminLoginRoute
  '/confirmacao/$id': typeof ConfirmacaoIdRoute
  '/oportunidade/$token': typeof OportunidadeTokenRoute
  '/profissional_/entrar': typeof ProfissionalEntrarRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/auth'
    | '/contratar'
    | '/entrar'
    | '/minha-conta'
    | '/privacidade'
    | '/profissional'
    | '/seja-profissional'
    | '/termos'
    | '/admin/avaliacoes'
    | '/admin/cancelamentos'
    | '/admin/carrossel'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/contratacoes'
    | '/admin/extras'
    | '/admin/lista-espera'
    | '/admin/orquestra'
    | '/admin/precos'
    | '/admin/profissionais'
    | '/admin/login'
    | '/confirmacao/$id'
    | '/oportunidade/$token'
    | '/profissional/entrar'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/auth'
    | '/contratar'
    | '/entrar'
    | '/minha-conta'
    | '/privacidade'
    | '/profissional'
    | '/seja-profissional'
    | '/termos'
    | '/admin/avaliacoes'
    | '/admin/cancelamentos'
    | '/admin/carrossel'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/contratacoes'
    | '/admin/extras'
    | '/admin/lista-espera'
    | '/admin/orquestra'
    | '/admin/precos'
    | '/admin/profissionais'
    | '/admin/login'
    | '/confirmacao/$id'
    | '/oportunidade/$token'
    | '/profissional/entrar'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajuda'
    | '/auth'
    | '/contratar'
    | '/entrar'
    | '/minha-conta'
    | '/privacidade'
    | '/profissional'
    | '/seja-profissional'
    | '/termos'
    | '/admin/avaliacoes'
    | '/admin/cancelamentos'
    | '/admin/carrossel'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/contratacoes'
    | '/admin/extras'
    | '/admin/lista-espera'
    | '/admin/orquestra'
    | '/admin/precos'
    | '/admin/profissionais'
    | '/admin_/login'
    | '/confirmacao/$id'
    | '/oportunidade/$token'
    | '/profissional_/entrar'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  AuthRoute: typeof AuthRoute
  ContratarRoute: typeof ContratarRoute
  EntrarRoute: typeof EntrarRoute
  MinhaContaRoute: typeof MinhaContaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProfissionalRoute: typeof ProfissionalRoute
  SejaProfissionalRoute: typeof SejaProfissionalRoute
  TermosRoute: typeof TermosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ConfirmacaoIdRoute: typeof ConfirmacaoIdRoute
  OportunidadeTokenRoute: typeof OportunidadeTokenRoute
  ProfissionalEntrarRoute: typeof ProfissionalEntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratar': {
      id: '/contratar'
      path: '/contratar'
      fullPath: '/contratar'
      preLoaderRoute: typeof ContratarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional': {
      id: '/profissional'
      path: '/profissional'
      fullPath: '/profissional'
      preLoaderRoute: typeof ProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-profissional': {
      id: '/seja-profissional'
      path: '/seja-profissional'
      fullPath: '/seja-profissional'
      preLoaderRoute: typeof SejaProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cancelamentos': {
      id: '/admin/cancelamentos'
      path: '/cancelamentos'
      fullPath: '/admin/cancelamentos'
      preLoaderRoute: typeof AdminCancelamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carrossel': {
      id: '/admin/carrossel'
      path: '/carrossel'
      fullPath: '/admin/carrossel'
      preLoaderRoute: typeof AdminCarrosselRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contratacoes': {
      id: '/admin/contratacoes'
      path: '/contratacoes'
      fullPath: '/admin/contratacoes'
      preLoaderRoute: typeof AdminContratacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/extras': {
      id: '/admin/extras'
      path: '/extras'
      fullPath: '/admin/extras'
      preLoaderRoute: typeof AdminExtrasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lista-espera': {
      id: '/admin/lista-espera'
      path: '/lista-espera'
      fullPath: '/admin/lista-espera'
      preLoaderRoute: typeof AdminListaEsperaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orquestra': {
      id: '/admin/orquestra'
      path: '/orquestra'
      fullPath: '/admin/orquestra'
      preLoaderRoute: typeof AdminOrquestraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/precos': {
      id: '/admin/precos'
      path: '/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AdminPrecosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profissionais': {
      id: '/admin/profissionais'
      path: '/profissionais'
      fullPath: '/admin/profissionais'
      preLoaderRoute: typeof AdminProfissionaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacao/$id': {
      id: '/confirmacao/$id'
      path: '/confirmacao/$id'
      fullPath: '/confirmacao/$id'
      preLoaderRoute: typeof ConfirmacaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidade/$token': {
      id: '/oportunidade/$token'
      path: '/oportunidade/$token'
      fullPath: '/oportunidade/$token'
      preLoaderRoute: typeof OportunidadeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional_/entrar': {
      id: '/profissional_/entrar'
      path: '/profissional/entrar'
      fullPath: '/profissional/entrar'
      preLoaderRoute: typeof ProfissionalEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminCancelamentosRoute: typeof AdminCancelamentosRoute
  AdminCarrosselRoute: typeof AdminCarrosselRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminContratacoesRoute: typeof AdminContratacoesRoute
  AdminExtrasRoute: typeof AdminExtrasRoute
  AdminListaEsperaRoute: typeof AdminListaEsperaRoute
  AdminOrquestraRoute: typeof AdminOrquestraRoute
  AdminPrecosRoute: typeof AdminPrecosRoute
  AdminProfissionaisRoute: typeof AdminProfissionaisRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminCancelamentosRoute: AdminCancelamentosRoute,
  AdminCarrosselRoute: AdminCarrosselRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminContratacoesRoute: AdminContratacoesRoute,
  AdminExtrasRoute: AdminExtrasRoute,
  AdminListaEsperaRoute: AdminListaEsperaRoute,
  AdminOrquestraRoute: AdminOrquestraRoute,
  AdminPrecosRoute: AdminPrecosRoute,
  AdminProfissionaisRoute: AdminProfissionaisRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AjudaRoute: AjudaRoute,
  AuthRoute: AuthRoute,
  ContratarRoute: ContratarRoute,
  EntrarRoute: EntrarRoute,
  MinhaContaRoute: MinhaContaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProfissionalRoute: ProfissionalRoute,
  SejaProfissionalRoute: SejaProfissionalRoute,
  TermosRoute: TermosRoute,
  AdminLoginRoute: AdminLoginRoute,
  ConfirmacaoIdRoute: ConfirmacaoIdRoute,
  OportunidadeTokenRoute: OportunidadeTokenRoute,
  ProfissionalEntrarRoute: ProfissionalEntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
